### PR TITLE
Get rid of deprecated Counter.Set() function

### PR DESCRIPTION
**Pull request by ledgr**

### CODE REVIEW

**Comment by ledgr** [comment]
Ping @janeczku

**Comment by janeczku** [comment]
@ledgr thanks for the PR! I assume the unit tests have to be fixed? :wink:

**Comment by thechile** [comment]
this PR seems to brake all gauge metrics.

**Comment by janeczku** [comment]
@ledgr could you revert changing indentation to spaces? It's impossible to review the patch here on GitHub as it is.

**Comment by ledgr** [comment]
Moving this to: https://github.com/janeczku/powerdns_exporter/pull/5

**Pull request closed without merging**
